services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: industry-payment-app
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "5011:5011"
    volumes:
      - uploads_data:/app/uploads/payment-proofs

volumes:
  uploads_data:
